version: '3.8'

services:
  powermad-server:
    build: ./server
    container_name: powermad-server
    hostname: powermad-server
    image: public.ecr.aws/k0r5u8i7/powermad-server:latest
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure

  powermad-client:
    build: ./client
    container_name: powermad-client
    image: public.ecr.aws/k0r5u8i7/powermad-client:latest
    ports:
      - 3000:3000
    # TODO: hot reload
    # volumes:
      # - ./src/:/app/src/
