/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Config_CONSTANTS_H
#define Config_CONSTANTS_H

#include "Config_types.h"

namespace DF { namespace Config {

class ConfigConstants {
 public:
  ConfigConstants();

  int32_t SchemaVersion;
  int32_t SchemaVersionMinCompatible;
  std::string DefaultMatch3ThemeId;
  std::string LevelEditorLevelCampaignId;
  std::string LevelEditorBuildingId;
  StoreTabID AllItemStoreTabId;
  std::string DailyAchievementGroupId;
  std::string ObjectiveAchievementGroupId;
  std::string OrderCollectAchievementGroupId;
  std::string BusinessExpanderAchievementGroupId;
  std::string BusinessPlaceAchievementGroupId;
  std::string DecoratorAchievementGroupId;
  std::string RoadDecoTypeName;
};

extern const ConfigConstants g_Config_constants;

}} // namespace

#endif
