/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Config_constants.h"

namespace DF { namespace Config {

const ConfigConstants g_Config_constants;

ConfigConstants::ConfigConstants() {
  SchemaVersion = 1;

  SchemaVersionMinCompatible = 1;

  DefaultMatch3ThemeId = "Default";

  LevelEditorLevelCampaignId = "C001-Business";

  LevelEditorBuildingId = "LevelEditor";

  AllItemStoreTabId = "All";

  DailyAchievementGroupId = "ACG_DailyAchievements";

  ObjectiveAchievementGroupId = "ACG_Objectives";

  OrderCollectAchievementGroupId = "ACG_OrderCollect";

  BusinessExpanderAchievementGroupId = "ACG_BusinessExpander";

  BusinessPlaceAchievementGroupId = "AGC_BusinessPlace";

  DecoratorAchievementGroupId = "ACG_Decorator";

  RoadDecoTypeName = "Transportation";

}

}} // namespace

