--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'

SchemaVersion = 1

SchemaVersionMinCompatible = 1

DefaultMatch3ThemeId = 'Default'

LevelEditorLevelCampaignId = 'C001-Business'

LevelEditorBuildingId = 'LevelEditor'

AllItemStoreTabId = 'All'

DailyAchievementGroupId = 'ACG_DailyAchievements'

ObjectiveAchievementGroupId = 'ACG_Objectives'

OrderCollectAchievementGroupId = 'ACG_OrderCollect'

BusinessExpanderAchievementGroupId = 'ACG_BusinessExpander'

BusinessPlaceAchievementGroupId = 'AGC_BusinessPlace'

DecoratorAchievementGroupId = 'ACG_Decorator'

RoadDecoTypeName = 'Transportation'